server:
  port: 8080
  servlet:
    context-path: /lms

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity"
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "U+NXeAi5ytRMjd8P5J7H6Upqm3Hvt7dyliIW5rosLvAGb3wiS6HBLj1UmbQgD485"
  valid-duration: 3600 #in second
  refreshable-duration: 36000 #in second

file:
  public-dir: ./uploads/public/
  private-dir: ./uploads/private/
  max-size: 20MB

recaptcha:
  secret: 6LcNlVArAAAAAABVgugTwNHe5zM34fIJmYC_lm8w